# AI Chat Moderator Configuration

# OpenAI API Configuration
openai:
  api-key: "your-api-key-here"
  endpoint: "https://api.openai.com/v1/moderations"
  request-timeout: 5000 # milliseconds

# Moderation Settings
moderation:
  # Enable/disable specific categories
  categories:
    harassment:
      enabled: true
      threshold: 0.8
      warning: "&cYour message was blocked for harassment."
    
    harassment/threatening:
      enabled: true
      threshold: 0.7
      warning: "&cYour message was blocked for threatening harassment."
    
    hate:
      enabled: true
      threshold: 0.8
      warning: "&cYour message was blocked for hate speech."
    
    hate/threatening:
      enabled: true
      threshold: 0.7
      warning: "&cYour message was blocked for threatening hate speech."
    
    illicit:
      enabled: true
      threshold: 0.8
      warning: "&cYour message was blocked for illicit content."
    
    illicit/violent:
      enabled: true
      threshold: 0.7
      warning: "&cYour message was blocked for violent illicit content."
    
    self-harm:
      enabled: true
      threshold: 0.8
      warning: "&cYour message was blocked for self-harm content."
    
    self-harm/intent:
      enabled: true
      threshold: 0.7
      warning: "&cYour message was blocked for self-harm intent."
    
    self-harm/instructions:
      enabled: true
      threshold: 0.7
      warning: "&cYour message was blocked for self-harm instructions."
    
    sexual:
      enabled: true
      threshold: 0.8
      warning: "&cYour message was blocked for sexual content."
    
    sexual/minors:
      enabled: true
      threshold: 0.7
      warning: "&cYour message was blocked for inappropriate content involving minors."
    
    violence:
      enabled: true
      threshold: 0.8
      warning: "&cYour message was blocked for violent content."
    
    violence/graphic:
      enabled: true
      threshold: 0.7
      warning: "&cYour message was blocked for graphic violent content."

# Link Detection
links:
  enabled: true
  warning: "&cLinks are not allowed in chat!"
  whitelist:
    - "minecraft.net"
    - "spigotmc.org"

# General Settings
settings:
  debug-mode: false
  log-blocked-messages: true
  notify-admins: true
  admin-notification-message: "&4[ModBot] &f{player} tried to send a blocked message: {message}"
  # Cache settings
  cache-duration: 300 # seconds to cache moderation results
  cache-max-size: 1000 # maximum number of cached entries
  async-timeout: 5000 # milliseconds to wait for async operations

# Messages
messages:
  prefix: "&8[&bModBot&8] &r"
  reload-success: "&aConfiguration reloaded successfully!"
  reload-failed: "&cFailed to reload configuration!"
  no-permission: "&cYou don't have permission to use this command!"
  processing-error: "&cFailed to process your message. Please try again later."
